name: edm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - numpy
  - click
  - pillow
  - scipy
  - pytorch
  - pytorch-cuda=12.4 # added this line
  - torchvision # added this line
  - psutil
  - requests
  - tqdm
  - imageio
  - matplotlib
  - pandas
  - diffusers # added this line
  - einops # added this line
  - accelerate # added this line
  - wandb # added this line
  - pip
  - pip:
    - imageio-ffmpeg
    - pyspng
    - ema-pytorch>=0.4.2 # added this line
    - medmnist # added this line